### ISSUE TITLE
Program Exception

### ISSUE THREAD

**Issue by Kysada** [CodingWonders/DISMTools#107]
**What is the bug about?**
Please describe the bug you're experiencing. Examples:

- *When doing something, the program crashes*

**How does it happen?**
Please provide the steps necessary to reproduce this bug:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by CodingWonders** [comment]
If you have the error information on your clipboard, please provide those details. Once they are provided, I'll reopen this issue
