### ISSUE TITLE
Program Exception

### ISSUE THREAD

**Issue by cevheraktunc** [CodingWonders/DISMTools#144]
![Screenshot 2024-07-28 221444](https://github.com/user-attachments/assets/b62c3dcb-50b0-4fc1-b226-372569d3cd43)
**What is the bug about?**
Please describe the bug you're experiencing. Examples:

- *When doing something, the program crashes*

**How does it happen?**
Please provide the steps necessary to reproduce this bug:

**Expected behavior**

**Screenshots**

**Additional context**

**NOTE:** in the case of a program exception, you need to paste the error information in the first section. Remove example information beforehand.

**Comment by CodingWonders** [comment]
The error information is copied to the clipboard. Can you paste it?

**Comment by cevheraktunc** [comment]
Sorry, ı cancelled it. When ı was see again ı Will copy.

28 Tem 2024 Pzr 22:30 tarihinde CodingWonders ***@***.***>
şunu yazdı:

**Comment by CodingWonders** [comment]
Alright, take your time.
