### ISSUE TITLE
Program Exception

### ISSUE THREAD

**Issue by Rollback-Jockey** [CodingWonders/DISMTools#147]
**What is the bug about?**
Please describe the bug you're experiencing. Examples:
System.UnauthorizedAccessException: Access to the path 'D:\Program Files\DISM Tools\update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at DISMTools.PrgAbout.UpdCheckBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Access to the path 'D:\Program Files\DISM Tools\update.exe' is denied.

Error Code (HRESULT): 80070005

Machine information:
 - Computer manufacturer: Packard Bell
 - Computer model: oneTwo L5351
 - BIOS name/description: Default System BIOS Default System BIOS
 - System Management BIOS (SMBIOS) version: P01-B2

Operating system information:
 - OS name: Microsoft Windows 11 Enterprise
 - OS version: 10.0.22631.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: AMD Athlon(tm) II X4 605e Processor
 - Processor caption: AMD64 Family 16 Model 5 Stepping 3
 - Processor manufacturer: AuthenticAMD
 - Processor family (WMI type): 1
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.
- *When doing something, the program crashes* 
Checking for updates

**How does it happen?**
Please provide the steps necessary to reproduce this bug: 
Selecting check for updates

**Expected behavior**

**Screenshots**

**Additional context**

**NOTE:** in the case of a program exception, you need to paste the error information in the first section. Remove example information beforehand.

**Comment by CodingWonders** [comment]
What happens if you delete `update.exe` manually?
