### ISSUE TITLE
Hangs when has wlan connection

### ISSUE THREAD

**Issue by vadimlitvinenko87** [CodingWonders/DISMTools#151]
With turned off internet main window start project without hangs.
With turned on hangs forever, after turned off at this point windows starts as normal.

**Comment by CodingWonders** [comment]
This is because getting news and videos does not occur in a separate thread. This can happen for extended periods of time if your network connection is not fast. I'll work on moving them to separate threads

**Comment by CodingWonders** [comment]
I've added a possible fix for this. Give the latest nightly installer a whirl, and return with the results.

**Comment by CodingWonders** [comment]
I'm closing this issue since I deem it fixed. If it still happens, feel free to re-open it or create a new one.

Thanks for reporting it!
