### ISSUE TITLE
after mounting the image, the interface is not active!

### ISSUE THREAD

**Issue by AlFmla** [CodingWonders/DISMTools#155]
after mounting the image, the interface and functions is not active! v0.5.1_stable
OS Version= 23H2 22631.3155, Dism.exe version: 10.0.22621.2792
![error](https://github.com/user-attachments/assets/98c28d82-82d9-461d-80d9-6183e8a07b95)

**Comment by CodingWonders** [comment]
Reload the project. That's something that happens sometimes

**Comment by AlFmla** [comment]
> Reload the project. That's something that happens sometimes

Recreated the project and Reload the system, mounted different images, does not work. Does it work for you?

**Comment by CodingWonders** [comment]
> Reload, recreated the project and the system, mounted different images, does not work. Does it work for you?

Yes, it works for me. Can you share a video recording so that I can see what you're trying to do better?

**Comment by AlFmla** [comment]
Reload the project helped, but after the errors come out, it does not work with the image. And it works with the online installation.
Here is the video:
https://youtu.be/b7enI3sfjt0

**Comment by CodingWonders** [comment]
You could have just uploaded the video to GitHub. Anyway, I would need the WIM file - it could be an issue with it. Send a link to the image file

**Comment by AlFmla** [comment]
[iso torrent](https://comss.cloud/26120.1542.240811-1119.GE_RELEASE_SVC_BETAFLT_PROD1_CLIENTMULTI_X64FRE_RU-RU_FIXED_2024_08_20.iso.torrent)
The image of the worker, original. It doesn't work with me in any image. Probably something with my system.

**Comment by CodingWonders** [comment]
I'm sorry, but I can't seem to replicate the issue. It works correctly on my end.

Does it work correctly with other versions of DT? Preview releases? Older stable versions?

**Comment by AlFmla** [comment]
I reinstalled the system and the functions started working. There was a problem in my system, but everything used to work on my system, I can't say why it stopped working, sorry.

**Comment by CodingWonders** [comment]
@AlFmla, don't worry. It was fun tinkering and experimenting to try to get the root cause of the issue
