### ISSUE TITLE
Program Exception

### ISSUE THREAD

**Issue by glennsamuel32** [CodingWonders/DISMTools#159]
**What is the bug about?**
Please describe the bug you're experiencing. Examples:

- *When doing something, the program crashes*

> [!NOTE]
> In the case of an exception, its details have been copied to your clipboard. All you need to do is paste the information.
> 
> If it hasn't been copied to your clipboard, a local copy has been saved to the following location: `<program directory>\Logs\Errors`

**How does it happen?**
Please provide the steps necessary to reproduce this bug:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by CodingWonders** [comment]
@glennsamuel32, have you read the issue instructions? Specify the exception, or I'll close the issue
