### ISSUE TITLE
[FEATURE PROPOSAL] Open mount folder

### ISSUE THREAD

**Issue by Procstas** [CodingWonders/DISMTools#165]
**Describe the solution you'd like**
A button in the GUI to open the mountfolder in Windows Explorer would be a welcome and useful addition.

**Comment by CodingWonders** [comment]
Right now, you can access the mount directory by right-clicking "Mount directory" in the tree view and clicking "Access directory", or through the mounted image manager.

Still, it's a good proposal! Thanks @Procstas!

**Comment by Procstas** [comment]
“Access directory” opens the appdata folder

C:\Users\xxxxx\AppData\Local\DISMTools\MyProject\mount

I don’t want an wim-image to be mounted there.

**Comment by CodingWonders** [comment]
@Procstas, it depends on where you have mounted your image and where the project is located. Try creating another project somewhere else and mounting the image there.

By the way, **you don't have to reply via email**. Your replies will get bloated quickly. Simply type a message mentioning me with the at (@) symbol

**Comment by Procstas** [comment]
> @Procstas, it depends on where you have mounted your image and where the project is located. Try creating another project somewhere else and mounting the image there.
> 
The "Mount point - Access Directory" should refer to my choosen "Destination Mount directory" which can vary including my RAMdisk mount folder.

**Comment by CodingWonders** [comment]
Since the issue you described was fixed, I'm closing it. @Procstas, feel free to reopen it or create a new one
