### ISSUE TITLE
Installer issues - Icon in Windows control panel is not graphic / copyright message is empty

### ISSUE THREAD

**Issue by bovirus** [CodingWonders/DISMTools#189]
@CodingWonders 

**What is the bug about?**

Due problem in Inno Setup script 

the icon in Windows Control Panel to un install the program is generic icon,
Copyright info is instalelr exe file properties is empty
I'd like to modify InnOSetup script.
Wht's the starting yaer for copyright about your app?

- *When doing something, the program crashes*

**IF YOU HAVE ENCOUNTERED A PROGRAM EXCEPTION, YOU NEED TO USE ITS RESPECTIVE TEMPLATE. Go to the issue types and select "Program exception"**

**How does it happen?**
Run the installer

**Expected behavior**
Graphic icon in the installer
Copyright emssages in exe file poperties.

**Screenshots**

![image](https://github.com/user-attachments/assets/17340f00-83bc-4dee-bb3f-ee25ad7f9a0a)

![image](https://github.com/user-attachments/assets/d87eb726-e7dc-4a6c-b0c1-12122bcbb5c2)

**Additional context**

Thanks.

**Comment by CodingWonders** [comment]
@bovirus, follow the [contribution guidelines](https://github.com/CodingWonders/DISMTools/blob/stable/CONTRIBUTING.md) to make a pull request with your requested changes.

The installer script is `<repo directory>\Installer\dt.iss`. Modify it to your liking if you know Inno Setup and want to fix this problem

**Comment by bovirus** [comment]
@CodingWonders 

I will make a PR for Inno Setup

I have some doubt about your Inno Setup configuration and files on github repository.

In your original script Inno Setup script on github

https://github.com/CodingWonders/DISMTools/blob/stable/Installer/dt.iss

you have

Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "es"; MessagesFile: "compiler:Spanish.isl"
Name: "fr"; MessagesFile: "compiler:French.isl"
Name: "de"; MessagesFile: "compiler:German.isl"
Name: "it"; MessagesFile: "compiler:Italian.isl"
Name: "pt"; MessagesFile: "compiler:Portuguese.isl"

In the pc in Inno Setup the .isl language files (except Default.isl) are in "Languages" subfolder then if you want to sue .isl file in your pc the configuration should be

Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "es"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"
Name: "de"; MessagesFile: "compiler:Languages\German.isl"
Name: "it"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "pt"; MessagesFile: "compiler:Languages\Portuguese.isl"

In your github folder

https://github.com/CodingWonders/DISMTools/tree/stable/Installer

the files

Default.isl
French.isl
German.isl
Portugues.isl
Spanish.isl

seems not necwssary because you get them from Inno Setup folder in your pc.

**Comment by CodingWonders** [comment]
Fixed with PR #192. The issue will be closed
