### ISSUE TITLE
Can't remove volume images

### ISSUE THREAD

**Issue by Guarmanda** [CodingWonders/DISMTools#74]
**What is the bug about?**
can't remove volume images

**How does it happen?**
when trying to remove volume images, I just get errors

**Expected behavior**
volume images should be removed

**Screenshots**
![image](https://github.com/CodingWonders/DISMTools/assets/7463055/2c99b740-8a63-48e1-84d7-9b2697912e4f)

**Additional context**
using latest windows iso with nightly DISMTools installer

**Comment by CodingWonders** [comment]
Have you tried running the DISM delete image command manually to see what it returns? This could sometimes happen, so can you send the log file?

**Comment by Guarmanda** [comment]
I did the command by hand.
Removing image by index works, but not by name: dism doesn't find the image, maybe because it's french, idk
That being said, removing by name is better, because indexes are changed between two removal..
A workaround would be to remove by index, but getting the index for each chosen name, and redo the getimage-info command each time, to reload index (not good, I know)

**Comment by CodingWonders** [comment]
> A workaround would be to remove by index, but getting the index for each chosen name, and redo the getimage-info command each time, to reload index (not good, I know)

Or we could just do, if we were to remove indexes 3 and 7 from an image with 11 indexes: 1, 1, 2, 2, 2, 3... until we end. That is very complex and requires a lot of logic though that I'd rather not implement, since something could go wrong.

**Comment by CodingWonders** [comment]
I temporarily closed some of your issues to clean up the issue board. I'll revisit those issues later on, plan on ways to fix them, and reopen them if necessary.

Still, thanks for reporting all those issues!
