### ISSUE TITLE
Removing volume images requires to not mount the image, but we have to mount an image to click on the button

### ISSUE THREAD

**Issue by Guarmanda** [CodingWonders/DISMTools#75]
**What is the bug about?**
Removing volume images requires to not mount the image, but we have to mount an image to click on the button

**Expected behavior**
We should be able to remove volume images without mounting the image first

**Screenshots**
![image](https://github.com/CodingWonders/DISMTools/assets/7463055/0b875a25-67ee-482d-98a3-b4654584b217)

**Additional context**
 but anyway, the feature of removing images does not works, so...

**Comment by CodingWonders** [comment]
Thanks for providing feedback on the new design!

This design is not yet complete so some things may change. This involves changing the `Enabled` properties of some buttons. In the meantime, you can go to Commands > Image management > Delete volume image from image file...
