### ISSUE TITLE
"Delete driver" window doesn't show any driver

### ISSUE THREAD

**Issue by Guarmanda** [CodingWonders/DISMTools#77]
**What is the bug about?**
"Delete driver" window doesn't show any driver

**How does it happen?**
Load an image, click on "delete drivers"

**Expected behavior**
All preinstalled drivers are shown

**Screenshots**
![image](https://github.com/CodingWonders/DISMTools/assets/7463055/e3ab3b3d-5c2a-4783-9c8b-5e5078bf6391)

**Additional context**
using nightly build

**Comment by Guarmanda** [comment]
The "get driver information" has the same problem
![image](https://github.com/CodingWonders/DISMTools/assets/7463055/985bded1-abdd-4069-80e6-dd494e628f66)

**Comment by CodingWonders** [comment]
This is because, by default, the program doesn't show built-in drivers. The driver information dialog lets you change this setting (see message on the bottom). To remove third-party ones, you'll need to add them

**Comment by Guarmanda** [comment]
it is true, it now works :O sorry
