### ISSUE TITLE
Removing capability that is already uninstalled throws error 57

### ISSUE THREAD

**Issue by Guarmanda** [CodingWonders/DISMTools#78]
**What is the bug about?**
Removing any capability that are already removed throws error 57

**How does it happen?**
when removing capability that is already uninstalled, error 57 is thrown

**Expected behavior**
capability is succesfully removed, and only installed cabpabilities are shown

**Screenshots**
![image](https://github.com/CodingWonders/DISMTools/assets/7463055/da94b0f1-dd51-4a6e-bedd-38612291a5ec)

**Additional context**
using nightly build

**Comment by Guarmanda** [comment]
error in logs: Failed to find capability by name Media.WindowsMediaPlayer~~~~0.0.12.0. HR=0x80070490 - CPackageManagerCLIHandler::Private_GetCapabilitiesFromCommandLine

**Comment by CodingWonders** [comment]
What capability were you trying to remove? Can you share the information on that capability?

Just so you know, if you externally perform changes to a Windows image (using DISM commands), this program will not pick them up, so you need to reload the project.

**Comment by Guarmanda** [comment]
In another menu of your application, for example, I uninstalled windows defender. 
Then in capabilities, windows defender was already uninstalled, so selecting it for removal gave me an error.
